'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process');
const Ajv=require('ajv/dist/2020'),formats=require('ajv-formats');
const wrapper=require('../hooks/scripts/wrap-receipt-envelope.js'),env=require('../hooks/scripts/envelope.js'),j=require('../runtime/operation-journal.js');
const finish=require('../runtime/session-receipt-runtime.js');
const id='op-'+'a'.repeat(64),run='0'.repeat(26);
function goal(){return{required_ids:['REQ-001'],accepted_ids:['REQ-001'],complete:true};}
function payload(kind){return kind==='slice-receipt'?{schema_version:'1.1',slice_id:'SLICE-001',status:'complete',tdd:{mode:'not-applicable',state_transitions:[]},completion_basis:'outcome-v1',runtime_receipt_ref:{path:'.deep-work/s-1234abcd/runtime-receipts/SLICE-001.json',sha256:'b'.repeat(64),producer_operation_id:id},publication_operation_id:id,recovery_generation:0,goal_acceptance:goal()}:{schema_version:'1.1',session_id:'s-1234abcd',started_at:'2026-09-06T00:00:00Z',outcome:'keep',slices:{total:1,completed:1},quality_score:null,metric_version:2,execution_basis_counts:{strict_tdd_v2:0,outcome_v1:1},goal_acceptance:goal(),effect_facts:{outcome:'keep',invoked:false,adopted:false,state:'not-required',reference:null},publication_operation_id:id};}
function wrap(kind,p=payload(kind)){return wrapper.prepareRuntimeEnvelope({artifactKind:kind,payload:p,runId:run,sessionId:'s-1234abcd',parentRunId:run,generatedAt:'2026-09-06T00:00:00Z',producerVersion:env.loadProducerVersion(),git:{head:'a'.repeat(40),branch:'main',dirty:false}});}
for(const kind of ['slice-receipt','session-receipt'])test(`canonical ${kind} emitter conforms to registry 1.1 with unchanged M3 1.0`,()=>{const ajv=new Ajv({strict:true});formats(ajv);const schema=require(`../schemas/payload-registry/deep-work/${kind}/v1.1.schema.json`);const validate=ajv.compile(schema),w=wrap(kind);assert.equal(validate(w.payload),true,JSON.stringify(validate.errors));assert.equal(w.schema_version,'1.0');assert.equal(w.envelope.schema.version,'1.1');assert.equal(w.payload.schema_version,'1.1');assert.match(schema.$id,/claude-deep-suite\/main\/schemas\/payload-registry/);assert.equal(validate({...w.payload,forged:true}),false);assert.throws(()=>wrapper.validatePayloadV11(kind,{...w.payload,forged:true}),/schema/);});
test('outcome public receipt rejects invented TDD, goal acceptance and caller scores',()=>{assert.throws(()=>wrap('slice-receipt',{...payload('slice-receipt'),tdd:{state_transitions:['RED']}}),/schema/);assert.throws(()=>wrap('slice-receipt',{...payload('slice-receipt'),goal_acceptance:{required_ids:['REQ-001'],accepted_ids:[],complete:true}}),/goal/);assert.throws(()=>finish.validateAuthoredPayload(Buffer.from('{"quality_score":100}')),/runtime-field/);assert.throws(()=>finish.validateAuthoredPayload(Buffer.from('{')),/payload-json/);assert.deepEqual(finish.validateAuthoredPayload(Buffer.from('{}')),{});});
test('canonical public writer restores exact reserved bytes and rejects replacement drift',t=>{const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'dw-m3-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.mkdirSync(path.join(root,'.claude'));const state=path.join(root,'.claude/deep-work.s-1234abcd.md');fs.writeFileSync(state,'---\nsession_id: s-1234abcd\nwork_dir: .deep-work/s-1234abcd\n---\n');const platform=require('../runtime/platform.js');const stateCapability=platform.issueProjectStateCapability(root,state,{role:'session-state'}),work=path.join(root,'.deep-work/s-1234abcd');fs.mkdirSync(work,{recursive:true});const sessionCapability=platform.issueProjectStateCapability(root,work,{role:'session-work-dir',sessionStateCapability:stateCapability}),candidate=path.join(work,'session-receipt.json'),wrapped=wrap('session-receipt');const first=wrapper.publishRuntimeEnvelope({sessionCapability,candidate,wrapped}),bytes=fs.readFileSync(candidate);fs.unlinkSync(candidate);const restored=wrapper.publishRuntimeEnvelope({sessionCapability,candidate,wrapped});assert.deepEqual(restored,first);assert.deepEqual(fs.readFileSync(candidate),bytes);assert.throws(()=>wrapper.publishRuntimeEnvelope({sessionCapability,candidate,wrapped:wrap('session-receipt',{...payload('session-receipt'),'x-extra':'drift'})}),/drift/);});
test('effect facts distinguish actual invocation, crash adoption and keep',()=>{assert.deepEqual(finish.effectFacts('keep',null,{stages:[]}),{outcome:'keep',invoked:false,adopted:false,state:'not-required',reference:null});const result=finish.effectFacts('publish-pr',{prStatus:'adopted',pushStatus:'adopted',prUrl:'https://example.invalid/pr/1'},{stages:[{stage:'before-call-1'},{stage:'after-call-before-stage-1',details:{owned:{adopted:true}}}]});assert.equal(result.invoked,true);assert.equal(result.adopted,true);assert.equal(result.state,'succeeded');});
test('metrics CLI rejects caller JSON authority and preserves failure exit',()=>{const result=cp.spawnSync(process.execPath,[path.resolve(__dirname,'../scripts/session-metrics-cli.js'),'--observations-json','{"quality_score":100}'],{encoding:'utf8'});assert.equal(result.status,1);assert.match(result.stderr,/usage/);assert.equal(result.stdout,'');});
test('strict M3 carries only observed refactor and sensor transitions',()=>{const observed=require('../runtime/completion-receipt-runtime.js').observedTdd;const slice={slice_kind:'functional',execution_basis:'strict-tdd-v2'};const noChange=observed({receipt:{refactor_evidence:{kind:'no-refactor',sensor_results:[]}}},slice);assert.deepEqual(noChange.state_transitions,['RED_VERIFIED','GREEN']);assert.equal(noChange.refactor_decision,'no-refactor');const performed=observed({receipt:{refactor_evidence:{kind:'performed-refactor',sensor_results:[{kind:'lint'}]}}},slice);assert.deepEqual(performed.state_transitions,['RED_VERIFIED','GREEN','REFACTOR_PENDING','GREEN','SENSOR_CLEAN']);const aggregate={...payload('slice-receipt'),completion_basis:'release-verification'};assert.doesNotThrow(()=>wrap('slice-receipt',aggregate));assert.throws(()=>wrap('slice-receipt',{...aggregate,tdd:{mode:'strict',state_transitions:['RED']}}),/schema/);});

function realManagedGit(t){const parent=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'dw-finish-effects-'))),root=path.join(parent,'repo');fs.mkdirSync(root);t.after(()=>fs.rmSync(parent,{recursive:true,force:true}));const git=(args,cwd=root)=>cp.execFileSync('git',args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe']});git(['init','-q','-b','main']);git(['config','user.name','Finish fixture']);git(['config','user.email','fixture@example.invalid']);fs.writeFileSync(path.join(root,'README.md'),'before\n');fs.writeFileSync(path.join(root,'.gitignore'),'.claude/\n');git(['add','README.md','.gitignore']);git(['commit','-qm','base']);const sessionId='s-1234abcd',branch='main-fork-1234abcd',child=path.join(parent,'repo-wt-fork-1234abcd');git(['worktree','add','-q','-b',branch,child]);fs.writeFileSync(path.join(child,'README.md'),'after\n');git(['add','README.md'],child);git(['commit','-qm','child'],child);fs.mkdirSync(path.join(root,'.claude'));const statePath=path.join(root,'.claude',`deep-work.${sessionId}.md`);const stateFields={session_id:sessionId,parent_branch:'main',branch,worktree_path:child,worktree_enabled:true};fs.writeFileSync(statePath,'---\n'+Object.entries(stateFields).map(([k,v])=>`${k}: ${JSON.stringify(v)}`).join('\n')+'\n---\n');const p=require('../runtime/platform.js');return{root,child,branch,sessionId,stateFields,git,projectCapability:p.issueProjectStateCapability(root,root,{role:'project-root'}),stateCapability:p.issueProjectStateCapability(root,statePath,{role:'session-state'})};}
for(const outcome of ['merge','discard'])test(`real Git ${outcome} adopts return loss without duplicate effect`,async t=>{const f=realManagedGit(t),runtime=require('../runtime/git-runtime.js'),operation=await j.beginOperation({projectCapability:f.projectCapability,sessionId:f.sessionId,kind:`finish-${outcome}`,preconditions:{fixture:'real-local-effect',outcome}});const counts={merge:0,remove:0,delete:0},run=async args=>{if(args[0]==='merge')counts.merge++;if(args[0]==='worktree'&&args[1]==='remove')counts.remove++;if(args[0]==='branch'&&['-d','-D'].includes(args[1]))counts.delete++;const result=cp.spawnSync('git',args,{cwd:f.root,encoding:'utf8'});return{ok:result.status===0,stdout:result.stdout,stderr:result.stderr};};const call=seam=>runtime[outcome==='merge'?'finishMergeWithinOperation':'finishDiscardWithinOperation']({...f,operation,gitRunner:run,seam});let crashed=false;await assert.rejects(()=>call((name,detail)=>{if(!crashed&&(outcome==='merge'?name==='after-call-before-stage'&&detail.kind==='merge':name==='worktree-after-call-before-stage')){crashed=true;throw new Error('lost-effect-return');}}),/lost-effect-return/);const result=await call();assert.equal(result.status,outcome==='merge'?'merged':'discarded');assert.equal(counts.merge,outcome==='merge'?1:0);assert.equal(counts.remove,1);assert.equal(counts.delete,1);assert.equal(fs.existsSync(f.child),false);const again=await call();assert.deepEqual(again,result);assert.equal(counts.merge,outcome==='merge'?1:0);assert.equal(counts.remove,1);assert.equal(counts.delete,1);});

test('session start time comes from the initialization-reserved ULID without inventing now',()=>{const at='2026-09-06T01:02:03.000Z',id=env.generateUlid(Date.parse(at));assert.equal(finish.sessionStartedAt({session_m3_run_id:id}),at);assert.throws(()=>finish.sessionStartedAt({session_m3_run_id:'bad'}),/start-time/);});
test('sensor metric consumes proven N/A without treating contract coverage as sensor work',()=>{const verificationPlan={gates:[{id:'GATE-impacted-lint-typecheck',adapter:'sensor',disposition:'required'},{id:'GATE-requirement-coverage',adapter:'contract',disposition:'advisory'}]},pkg={records:[{gate_id:'GATE-impacted-lint-typecheck',kind:'sensor',status:'pass',applicability:'not-applicable',producer_proof:{}}]};assert.deepEqual(finish.sensorMetricObservation(verificationPlan,pkg),{status:'not-applicable',reason:'authenticated capability evidence'});assert.deepEqual(finish.sensorMetricObservation(verificationPlan,{records:[]}),{status:'unknown'});});
test('a new Finish operation on terminal state rejects before any external effect',async t=>{const f=realManagedGit(t),state=path.join(f.root,'.claude',`deep-work.${f.sessionId}.md`),workDir=path.join(f.root,'.deep-work',f.sessionId);fs.mkdirSync(workDir,{recursive:true});const original='---\nsession_id: '+f.sessionId+'\nwork_dir: .deep-work/'+f.sessionId+'\ncurrent_phase: idle\nfinished_at: "2026-09-06T00:00:00Z"\n---\n';fs.writeFileSync(state,original);const platform=require('../runtime/platform.js'),stateCapability=platform.issueProjectStateCapability(f.root,state,{role:'session-state'}),sessionCapability=platform.issueProjectStateCapability(f.root,workDir,{role:'session-work-dir',sessionStateCapability:stateCapability});let calls=0;await assert.rejects(()=>finish.finishSessionV3({stateCapability,projectCapability:f.projectCapability,sessionId:f.sessionId,outcome:'merge',identities:[{purpose:'receipt-payload',operationId:'op-'+'c'.repeat(64),sessionCapability}],gitRunner:async()=>{calls++;throw new Error('unexpected-effect');}}),/finish-session-terminal/);assert.equal(calls,0);assert.equal(fs.readFileSync(state,'utf8'),original);assert.equal(fs.existsSync(f.child),true);});
