'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process'),Module=require('node:module');
const platform=require('../runtime/platform.js'),j=require('../runtime/operation-journal.js'),tx=require('../runtime/transaction-runtime.js'),artifact=require('../runtime/artifact-runtime.js'),fm=require('../runtime/frontmatter.js');
const realCompletion=require('../runtime/completion-receipt-runtime.js');
// Only the expensive goal/reviewer admission is a deterministic test double.
// Real Git, owned inputs, journal, Test producer identity, preparation, effects,
// recovery and terminal publication run unchanged. No fixture is provider proof.
function runtimeFor(f,{baseline=false}={}){
 const filename=path.resolve(__dirname,'../runtime/session-receipt-runtime.js'),source=global.__finishReviewSource?global.__finishReviewSource(filename,baseline):fs.readFileSync(filename,'utf8');
 const m=new Module(filename,module);m.filename=filename;m.paths=Module._nodeModulePaths(path.dirname(filename));
 const originalRequire=m.require.bind(m);
 m.require=name=>{if(name==='./governed-context-runtime.js')return{loadGovernedContext:()=>f.context(),selectGovernedAdmission:()=>({allowed:f.admitted(),blocking_codes:f.admitted()?[]:['fixture-authority-stale']})};
  if(name==='./completion-receipt-runtime.js')return{...realCompletion,authenticateSlicePublication:()=>({goal_acceptance:{required_ids:['REQ-001'],accepted_ids:['REQ-001'],complete:true},publication:{sha256:'a'.repeat(64)}})};
  if(name==='./evidence-runtime.js')return{loadCommittedPackage:()=>null};
  if(global.__finishReviewRequire){const patched=global.__finishReviewRequire(name,filename,baseline);if(patched)return patched;}
  return originalRequire(name);};m._compile(source,filename);return m.exports;
}
async function fixture(t,{outcome='discard'}={}){const parent=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'dw-finish-freshness-'))),root=path.join(parent,'repo');fs.mkdirSync(root);t.after(()=>fs.rmSync(parent,{recursive:true,force:true}));const git=(args,input)=>cp.execFileSync('git',args,{cwd:root,encoding:'utf8',input,stdio:['pipe','pipe','pipe']});git(['init','-q','-b','feature']);git(['config','user.name','Finish fixture']);git(['config','user.email','fixture@example.invalid']);fs.writeFileSync(path.join(root,'README.md'),'ready\n');fs.writeFileSync(path.join(root,'.gitignore'),'.claude/\n.deep-work/\n');git(['add','README.md','.gitignore']);git(['commit','-qm','initial']);git(['branch','main']);git(['remote','add','origin','https://github.com/fixture/repo.git']);fs.mkdirSync(path.join(root,'.claude'));const sessionId='s-1234abcd',child=path.join(parent,'repo-wt-fork-1234abcd');git(['worktree','add','-q','-b','main-fork-1234abcd',child]);const workDir=path.join(root,'.deep-work',sessionId);fs.mkdirSync(workDir,{recursive:true});const statePath=path.join(root,'.claude',`deep-work.${sessionId}.md`),planPath=path.join(workDir,'plan.json'),plan={schema_version:3,plan_authority_sha256:'b'.repeat(64),slices:[{id:'SLICE-001',slice_kind:'functional',execution_basis:'outcome-v1',contract:{requirements:['REQ-001'],invariants:[],failure_modes:[]}}]};fs.writeFileSync(planPath,JSON.stringify(plan));const initialPlanHash=j.sha256(fs.readFileSync(planPath)),projectCapability=platform.issueProjectStateCapability(root,root,{role:'project-root'});const fields={session_id:sessionId,work_dir:`.deep-work/${sessionId}`,current_phase:'test',session_m3_run_id:require('../hooks/scripts/envelope.js').generateUlid(),base_branch:'main',parent_branch:'main',branch:outcome==='discard'?'main-fork-1234abcd':'feature',worktree_enabled:outcome==='discard',worktree_path:outcome==='discard'?child:null,test_passed:true,test_completed_at:'2026-09-07T00:00:00Z',test_pass_operation_id:null,verification_plan_sha256:'c'.repeat(64),gate_results_sha256:'d'.repeat(64),receipt_recovery_generation:0,review_execution_json:'{}'};fs.writeFileSync(statePath,'---\n'+Object.entries(fields).map(([k,v])=>`${k}: ${JSON.stringify(v)}`).join('\n')+'\n---\n');const cap=()=>platform.issueProjectStateCapability(root,statePath,{role:'session-state'}),read=()=>tx.readState(cap()),patch=values=>platform.atomicWriteFile(cap(),fm.updateFrontmatterText(fs.readFileSync(statePath,'utf8'),values));
 const testProducer=async()=>{const current=read(),op=await j.beginOperation({projectCapability,sessionId,kind:'test-pass',preconditions:{fixture:'identity-only',nonce:Math.random()}});await j.completeOperation(op,{test_authority:{verification_plan_sha256:current.verification_plan_sha256,gate_results_sha256:current.gate_results_sha256,package_sha256:'e'.repeat(64),recovery_generation:current.receipt_recovery_generation,test_completed_at:current.test_completed_at}});patch({test_pass_operation_id:op.operationId});};await testProducer();fs.writeFileSync(path.join(root,'.claude','deep-work-sessions.json'),JSON.stringify({version:1,shared_files:[],sessions:{[sessionId]:{pid:process.pid,task_description:'fixture',work_dir:`.deep-work/${sessionId}`,current_phase:'test',file_ownership:[],last_activity:'2026-09-07T00:00:00Z'}}}));
 const sessionCap=()=>platform.issueProjectStateCapability(root,workDir,{role:'session-work-dir',sessionStateCapability:cap()}),identities=[];for(const[purpose,bytes]of (outcome==='discard'?[['receipt-payload','{}']]:[['receipt-payload','{}'],['pr-title','Prepared change'],['pr-body','Exact prepared body']])){const sc=sessionCap(),owned=await artifact.createOwnedTemp({sessionCapability:sc,purpose});await artifact.writeOwnedTemp({sessionCapability:sc,operationId:owned.operationId,purpose},Buffer.from(bytes));identities.push({sessionCapability:sc,purpose,operationId:owned.operationId});}
 let remoteHead=null,pr=null;const counts=outcome==='discard'?{remove:0,delete:0}:{push:0,create:0},head=git(['rev-parse','HEAD']).trim();const gitRunner=async args=>{if(args[0]==='worktree'&&args[1]==='remove')counts.remove++;if(args[0]==='branch'&&['-d','-D'].includes(args[1]))counts.delete++;if(args[0]==='ls-remote')return{ok:true,stdout:remoteHead?`${remoteHead}\trefs/heads/feature\n`:'',stderr:''};if(args[0]==='push'){counts.push++;remoteHead=head;if(f.afterPush)f.afterPush();return{ok:true,stdout:'pushed',stderr:''};}const r=cp.spawnSync('git',args,{cwd:root,encoding:'utf8'});return{ok:r.status===0,stdout:r.stdout,stderr:r.stderr};};const ghRunner=async args=>{if(args[0]==='auth')return{ok:true,stdout:'authenticated',stderr:''};if(args[1]==='list')return{ok:true,stdout:JSON.stringify(pr?[pr]:[]),stderr:''};if(args[1]==='create'){const bodyPath=args[args.indexOf('--body-file')+1];assert.equal(fs.readFileSync(bodyPath,'utf8'),'Exact prepared body');assert.equal(path.dirname(bodyPath),path.join(root,'.claude'));counts.create++;pr={number:1,id:'PR_fixture',url:'https://github.com/fixture/repo/pull/1',title:'Prepared change',body:'Exact prepared body',headRefOid:head,headRefName:'feature',baseRefName:'main'};return{ok:true,stdout:pr.url,stderr:''};}throw Error('unexpected provider command');};
 const f={root,workDir,sessionId,statePath,outcome,planPath,git,read,patch,testProducer,counts,projectCapability,cap,identities,gitRunner,ghRunner};f.admitted=()=>fs.readFileSync(path.join(root,'README.md'),'utf8')==='ready\n'&&j.sha256(fs.readFileSync(planPath))===initialPlanHash&&read().test_passed===true;f.context=()=>{const current=read(),plan=JSON.parse(fs.readFileSync(planPath));return{plan,verificationPlan:{plan_sha256:current.verification_plan_sha256,gates:[]},workDir,sha256:j.sha256(j.canonicalJson({plan,source:fs.readFileSync(path.join(root,'README.md'),'utf8')})),projection:{plan_identity:{status:'current'},receipts:{status:'complete',rows:[{slice_id:'SLICE-001',status:'complete'}]},evidence:{status:'complete',completed_ids:[]}}};};f.call=(runtime,seam)=>require('../runtime/session-store.js').withFinishTransaction({sessionId,stateCapability:cap(),outcome,force:outcome==='discard'},({caps})=>runtime.finishSessionV3({stateCapability:cap(),sessionId,outcome,force:outcome==='discard',projectCapability,caps,identities:identities.map(identity=>({...identity,sessionCapability:sessionCap()})),gitRunner,ghRunner,seam}));return f;}
function publicCall(f,runtime,seam){const routesFile=path.resolve(__dirname,'../runtime/dispatcher-routes.js'),routes=new Module(routesFile,module);routes.filename=routesFile;routes.paths=Module._nodeModulePaths(path.dirname(routesFile));const req=routes.require.bind(routes);routes.require=name=>name==='./session-receipt-runtime.js'?{...runtime,finishSessionV3:args=>runtime.finishSessionV3({...args,gitRunner:f.gitRunner,ghRunner:f.ghRunner,seam})}:req(name);routes._compile(fs.readFileSync(routesFile,'utf8'),routesFile);const entryFile=path.resolve(__dirname,'../scripts/deep-work-runtime.js'),entry=new Module(entryFile,module);entry.filename=entryFile;entry.paths=Module._nodeModulePaths(path.dirname(entryFile));const entryReq=entry.require.bind(entry);entry.require=name=>name==='../runtime/dispatcher-routes.js'?routes.exports:entryReq(name);entry._compile(fs.readFileSync(entryFile,'utf8'),entryFile);const source=purpose=>{const row=f.identities.find(i=>i.purpose===purpose);return path.join(f.workDir,'.tmp',row.operationId,purpose+'.tmp');};return entry.exports.dispatch(['session','finish','publish-pr','--state',f.statePath,'--session',f.sessionId,'--receipt-payload',source('receipt-payload'),'--title-file',source('pr-title'),'--body-file',source('pr-body')],{cwd:f.root});}
function crashAtPrepared(name){if(name==='after-completion-prepared')throw Error('prepared-crash');}
for(const drift of ['source','plan','verification','generation','test','fresh-test-operation','repository-index'])test(`prepared Finish rejects ${drift} drift before a new effect`,async t=>{const f=await fixture(t),runtime=runtimeFor(f);await assert.rejects(()=>f.call(runtime,crashAtPrepared),/prepared-crash/);const files=fs.readdirSync(path.join(f.root,'.claude')).filter(x=>x.includes('.op.finish-discard.'));assert.equal(files.length,1);const journal=JSON.parse(fs.readFileSync(path.join(f.root,'.claude',files[0])));assert(journal.stages.some(row=>row.stage==='completion-prepared'));if(drift==='source')fs.writeFileSync(path.join(f.root,'README.md'),'changed\n');if(drift==='plan'){const p=JSON.parse(fs.readFileSync(f.planPath));p.plan_authority_sha256='f'.repeat(64);fs.writeFileSync(f.planPath,JSON.stringify(p));}if(drift==='verification')f.patch({verification_plan_sha256:'f'.repeat(64)});if(drift==='generation')f.patch({receipt_recovery_generation:1});if(drift==='test')f.patch({test_passed:false});if(drift==='fresh-test-operation')await f.testProducer();if(drift==='repository-index'){const blob=f.git(['hash-object','-w','--stdin'],'other staged contents').trim();f.git(['update-index','--cacheinfo','100644',blob,'README.md']);}let rejected=false;try{await f.call(runtime);}catch{rejected=true;}assert.equal(f.counts.remove,0,'stale prepared replay invoked worktree removal');assert.equal(f.counts.delete,0,'stale prepared replay invoked branch deletion');assert.equal(rejected,true);});
test('unchanged preparation replay completes once and exact completed bytes are adopted',async t=>{const f=await fixture(t),runtime=runtimeFor(f);await assert.rejects(()=>f.call(runtime,crashAtPrepared),/prepared-crash/);const result=await f.call(runtime);assert.equal(result.status,'completed');assert.deepEqual(f.counts,{remove:1,delete:1});const bytes=fs.readFileSync(path.join(f.root,result.publication.path));const replay=await f.call(runtime);assert.equal(replay.publication.sha256,result.publication.sha256);assert.deepEqual(fs.readFileSync(path.join(f.root,result.publication.path)),bytes);assert.deepEqual(f.counts,{remove:1,delete:1});});
for(const seam of ['after-effect-before-verification','remove-return-loss'])test(`completed effect reconciles ${seam} without repeating actions after drift`,async t=>{const f=await fixture(t),runtime=runtimeFor(f);await assert.rejects(()=>f.call(runtime,(name)=>{if(name===seam||seam==='remove-return-loss'&&name==='worktree-after-call-before-stage')throw Error('effect-return-lost');}),/effect-return-lost/);assert.equal(f.counts.remove,1);fs.writeFileSync(path.join(f.root,'README.md'),'changed\n');await assert.rejects(()=>f.call(runtime));assert.deepEqual(f.counts,{remove:1,delete:1});fs.writeFileSync(path.join(f.root,'README.md'),'ready\n');assert.equal((await f.call(runtime)).status,'completed');assert.deepEqual(f.counts,{remove:1,delete:1});});
test('legacy prepared operation revalidates current authority and preserves exact replay',async t=>{const f=await fixture(t),runtime=runtimeFor(f);await assert.rejects(()=>f.call(runtime,crashAtPrepared),/prepared-crash/);const dir=path.join(f.root,'.claude'),file=fs.readdirSync(dir).find(name=>name.includes('.op.finish-discard.')),pending=JSON.parse(fs.readFileSync(path.join(dir,file))),request={...pending.preconditions};delete request.finish_authority;delete request.request_sha256;const legacyId='op-'+j.sha256(j.canonicalJson({kind:'finish-discard',...request}));if(legacyId!==pending.operationId){const legacy=await j.beginOperation({projectCapability:f.projectCapability,sessionId:f.sessionId,kind:'finish-discard',operationId:legacyId,preconditions:request}),prepared=structuredClone(pending.stages.find(row=>row.stage==='completion-prepared').details.owned);delete prepared.finish_authority;prepared.basePayload.publication_operation_id=legacyId;await j.recordOperationStage(legacy,'completion-prepared',{owned:prepared});}const result=await f.call(runtime);assert.equal(result.status,'completed');assert.equal(result.operationId,legacyId);assert.deepEqual(f.counts,{remove:1,delete:1});});

test('public V3 PR uses exact branded body and preserves completed replay bytes',async t=>{const f=await fixture(t,{outcome:'publish-pr'}),runtime=runtimeFor(f);await assert.rejects(()=>publicCall(f,runtime,crashAtPrepared),/prepared-crash/);const result=await publicCall(f,runtime);assert.equal(result.status,'completed');assert.deepEqual(f.counts,{push:1,create:1});const bytes=fs.readFileSync(path.join(f.root,result.publication.path)),replay=await publicCall(f,runtime);assert.equal(replay.publication.sha256,result.publication.sha256);assert.deepEqual(fs.readFileSync(path.join(f.root,result.publication.path)),bytes);assert.deepEqual(f.counts,{push:1,create:1});});
test('public prepared PR rejects stale source before push or create',async t=>{const f=await fixture(t,{outcome:'publish-pr'}),runtime=runtimeFor(f);await assert.rejects(()=>publicCall(f,runtime,crashAtPrepared),/prepared-crash/);fs.writeFileSync(path.join(f.root,'README.md'),'changed\n');await assert.rejects(()=>publicCall(f,runtime));assert.deepEqual(f.counts,{push:0,create:0});});
test('public PR push return-loss never authorizes remaining create after drift',async t=>{const f=await fixture(t,{outcome:'publish-pr'}),runtime=runtimeFor(f);await assert.rejects(()=>publicCall(f,runtime,(name,detail)=>{if(name==='after-call-before-stage'&&detail.kind==='remote-push')throw Error('push-return-lost');}),/push-return-lost/);fs.writeFileSync(path.join(f.root,'README.md'),'changed\n');await assert.rejects(()=>publicCall(f,runtime));assert.deepEqual(f.counts,{push:1,create:0});});
test('public PR create return-loss adopts existing effect without duplicates after drift',async t=>{const f=await fixture(t,{outcome:'publish-pr'}),runtime=runtimeFor(f);await assert.rejects(()=>publicCall(f,runtime,(name,detail)=>{if(name==='after-call-before-stage'&&detail.kind==='pull-request-create')throw Error('create-return-lost');}),/create-return-lost/);fs.writeFileSync(path.join(f.root,'README.md'),'changed\n');await assert.rejects(()=>publicCall(f,runtime));assert.deepEqual(f.counts,{push:1,create:1});fs.writeFileSync(path.join(f.root,'README.md'),'ready\n');assert.equal((await publicCall(f,runtime)).status,'completed');assert.deepEqual(f.counts,{push:1,create:1});});

test('public PR call intent without execution cannot bypass fresh authority',async t=>{const f=await fixture(t,{outcome:'publish-pr'}),runtime=runtimeFor(f);await assert.rejects(()=>publicCall(f,runtime,(name,detail)=>{if(name==='before-call'&&detail.kind==='remote-push')throw Error('intent-only-crash');}),/intent-only-crash/);assert.deepEqual(f.counts,{push:0,create:0});f.patch({test_passed:false});await assert.rejects(()=>publicCall(f,runtime));assert.deepEqual(f.counts,{push:0,create:0});});
test('fresh Finish ID and prepared stage bind the observed Test, source and repository authority',async t=>{const f=await fixture(t),runtime=runtimeFor(f);await assert.rejects(()=>f.call(runtime,crashAtPrepared),/prepared-crash/);const filename=fs.readdirSync(path.join(f.root,'.claude')).find(name=>name.includes('.op.finish-discard.')),row=JSON.parse(fs.readFileSync(path.join(f.root,'.claude',filename))),authority=row.preconditions.finish_authority;assert.equal(authority.test_pass_operation_id,f.read().test_pass_operation_id);assert.equal(authority.verification_plan_sha256,f.read().verification_plan_sha256);assert.equal(authority.recovery_generation,0);assert.match(authority.source_sha256,/^[a-f0-9]{64}$/);assert.equal(authority.repository.head,f.git(['rev-parse','HEAD']).trim());assert.deepEqual(row.stages.find(s=>s.stage==='completion-prepared').details.owned.finish_authority,authority);assert.equal(row.operationId,'op-'+j.sha256(j.canonicalJson({kind:'finish-discard',...row.preconditions})));});
test('prepared Finish rejects changed managed worktree contents before force removal',async t=>{const f=await fixture(t),runtime=runtimeFor(f);await assert.rejects(()=>f.call(runtime,crashAtPrepared),/prepared-crash/);const child=f.read().worktree_path;fs.writeFileSync(path.join(child,'README.md'),'new work after preparation\n');await assert.rejects(()=>f.call(runtime));assert.deepEqual(f.counts,{remove:0,delete:0});assert.equal(fs.readFileSync(path.join(child,'README.md'),'utf8'),'new work after preparation\n');});

test('each unexecuted PR effect rechecks authority even within one invocation',async t=>{const f=await fixture(t,{outcome:'publish-pr'}),runtime=runtimeFor(f);f.afterPush=()=>fs.writeFileSync(path.join(f.root,'README.md'),'changed by push-side effect\n');await assert.rejects(()=>publicCall(f,runtime));assert.deepEqual(f.counts,{push:1,create:0});});

test('prepared authority cannot substitute another snapshot under the bound operation ID',async t=>{const f=await fixture(t),runtime=runtimeFor(f);await assert.rejects(()=>f.call(runtime,crashAtPrepared),/prepared-crash/);const dir=path.join(f.root,'.claude'),filename=fs.readdirSync(dir).find(name=>name.includes('.op.finish-discard.')),file=path.join(dir,filename),row=JSON.parse(fs.readFileSync(file));row.stages.find(r=>r.stage==='completion-prepared').details.owned.finish_authority.test_pass_operation_id='op-'+'f'.repeat(64);fs.writeFileSync(file,j.canonicalJson(row));await assert.rejects(()=>f.call(runtime),/finish-authority-prepared/);assert.deepEqual(f.counts,{remove:0,delete:0});});
