'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process');
const plugin=path.resolve(__dirname,'..'),script=path.join(plugin,'scripts/deep-work-runtime.js');
function fixture(t,args,task='Update README wording',profileDefaults={}){
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'dw-policy-input-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.mkdirSync(path.join(root,'.git'));fs.writeFileSync(path.join(root,'.git/HEAD'),'a'.repeat(40)+'\n');fs.writeFileSync(path.join(root,'README.md'),'fixture');
 const save=(name,data)=>{const p=path.join(root,name);fs.writeFileSync(p,typeof data==='string'?data:JSON.stringify(data));return p;};const cli=args=>{const out=cp.spawnSync(process.execPath,[script,...args],{cwd:root,encoding:'utf8',env:{...process.env,DEEP_WORK_SESSION_ID:''}});if(out.status!==0)throw new Error(out.stderr);return JSON.parse(out.stdout);};
 const parsed=cli(['flags','parse','--arguments-json',save('args.json',args)]),taskFile=save('task.txt',task),init=cli(['session','initialize','--task-file',taskFile,'--flags-json',save('flags.json',parsed),'--profile-json',save('profile.json',{defaults:profileDefaults})]),prepared=cli(['session','repository','prepare','--session',init.sessionId,'--mode',init.mode,'--task-file',taskFile,'--defaults-json',save('effective.json',init.defaults)]),stateFile=prepared.stateCapability.path,fields=()=>require('../runtime/frontmatter.js').parseFrontmatter(fs.readFileSync(stateFile,'utf8')).fields;
 return{root,cli,save,taskFile,parsed,init,stateFile,fields};
}
function requirements(f){const fields=f.fields(),risk=JSON.parse(fields.risk_profile_json).class,verificationPlan={risk_class:risk};return{global:require('../runtime/global-review-runtime.js').globalReviewRequirements({fields,verificationPlan}),oracle:require('../runtime/outcome-review-runtime.js').reviewRequirements({fields,verificationPlan,slice:{contract:{risk:{class:risk},review_policy:'single'}}})};}
test('actual parsed shadow and dual Low survive initialization and require both review roles',t=>{const f=fixture(t,['--policy=shadow','--review=dual','--risk=low']);assert.equal(f.init.defaults.methodology_policy,'shadow');assert.equal(f.init.defaults.review_mode_override,'dual');assert.equal(f.fields().methodology_policy_mode,'shadow');assert.equal(JSON.parse(f.fields().methodology_policy_json).mode,'shadow');assert.equal(f.fields().review_mode_override,'dual');assert.equal(f.fields().requested_risk_class,'low');const rows=requirements(f);for(const reviewers of Object.values(rows))assert.deepEqual(reviewers.map(r=>r.role).sort(),['executability','semantic']);const before=fs.readFileSync(f.stateFile);f.cli(['session','authority','validate','--state',f.stateFile]);assert.deepEqual(fs.readFileSync(f.stateFile),before);});
test('explicit requested High raises the floor and single cannot remove required High roles',t=>{const f=fixture(t,['--policy=adaptive','--risk=high','--review=single']);assert.equal(JSON.parse(f.fields().risk_profile_json).class,'high');assert.equal(JSON.parse(f.fields().methodology_policy_json).risk_class,'high');assert.equal(f.fields().review_mode_override,'single');for(const reviewers of Object.values(requirements(f))){assert.deepEqual(reviewers.map(r=>r.role).sort(),['executability','semantic']);assert(reviewers.every(r=>r.tier==='deep'));}});
test('requested Low never downgrades an observed Critical destructive hard trigger',t=>{const f=fixture(t,['--risk=low','--review=single','--policy=shadow'],'Perform destructive schema migration');const risk=JSON.parse(f.fields().risk_profile_json);assert.equal(f.fields().requested_risk_class,'low');assert.equal(risk.class,'critical');assert(risk.hard_triggers.some(t=>t.min_class==='critical'));for(const reviewers of Object.values(requirements(f)))assert.deepEqual(reviewers.map(r=>r.role).sort(),['executability','semantic']);});
test('default adaptive auto leaves current risk unchanged and keeps normal Low single review',t=>{const f=fixture(t,[]);assert.equal(f.fields().methodology_policy_mode,'adaptive');assert.equal(f.fields().review_mode_override,'auto');assert.equal(f.fields().requested_risk_class,null);assert.equal(JSON.parse(f.fields().risk_profile_json).class,'low');for(const reviewers of Object.values(requirements(f)))assert.deepEqual(reviewers.map(r=>r.role),['semantic']);});
test('oracle role helper preserves old contexts without a stored session override',()=>{const rows=require('../runtime/outcome-review-runtime.js').reviewRequirements({verificationPlan:{risk_class:'low'},slice:{contract:{risk:{class:'low'},review_policy:'single'}}});assert.deepEqual(rows,[{role:'semantic',tier:'standard'}]);});
test('tagged parser defaults preserve profile shadow and dual when no CLI policy override was supplied',t=>{const f=fixture(t,[],'Update README wording',{methodology_policy:'shadow',review_mode_override:'dual'});assert.equal(f.parsed.parser_origin,'deep-work-flags-v1');assert.deepEqual(f.parsed.provided_options,[]);assert.equal(f.fields().methodology_policy_mode,'shadow');assert.equal(f.fields().review_mode_override,'dual');for(const rows of Object.values(requirements(f)))assert.deepEqual(rows.map(r=>r.role).sort(),['executability','semantic']);});
test('explicit adaptive and auto are distinguished from parser defaults and override the profile',t=>{const f=fixture(t,['--policy=adaptive','--review=auto'],'Update README wording',{methodology_policy:'shadow',review_mode_override:'dual'});assert.deepEqual(f.parsed.provided_options,['policy','review']);assert.equal(f.fields().methodology_policy_mode,'adaptive');assert.equal(f.fields().review_mode_override,'auto');assert.deepEqual(requirements(f).global,[{role:'semantic',tier:'standard'}]);});
test('invalid ignored CLI values never acquire provided-option authority over profile choices',t=>{const f=fixture(t,['--policy=invalid','--review=invalid','--risk=invalid'],'Update README wording',{methodology_policy:'shadow',review_mode_override:'dual'});assert.deepEqual(f.parsed.provided_options,[]);assert.equal(f.fields().methodology_policy_mode,'shadow');assert.equal(f.fields().review_mode_override,'dual');});
test('untagged direct flags retain supplied-key semantics without rewriting legacy parser output',t=>{const f=fixture(t,[]);const init=f.cli(['session','initialize','--task-file',f.taskFile,'--flags-json',f.save('raw-flags.json',{policy:'adaptive',review:'single'}),'--profile-json',f.save('raw-profile.json',{defaults:{methodology_policy:'shadow',review_mode_override:'dual'}})]);assert.equal(init.defaults.methodology_policy,'adaptive');assert.equal(init.defaults.review_mode_override,'single');assert.deepEqual(require('../runtime/flags-runtime.js').parseDeepWorkFlags([]),{tdd:null,team:null,positionals:[],execution:null});});
