'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const {createPublicWorkflowFixture}=require('./helpers/public-workflow-fixtures.js');const j=require('../runtime/operation-journal.js');
const childCode=`const fs=require('fs'),path=require('path'),r=process.argv[1],a=JSON.parse(process.argv[2]);const p=require(path.join(r,'platform.js')),tx=require(path.join(r,'transaction-runtime.js'));const state=p.issueProjectStateCapability(a.root,a.state,{role:'session-state'}),session=p.issueProjectStateCapability(a.root,a.workDir,{role:'session-work-dir',sessionStateCapability:state}),plan=tx.issueSessionFileCapability({sessionCapability:session,candidate:a.plan,allowedBasenames:['plan.json'],role:'locked-plan'});require(path.join(r,'outcome-verification-runtime.js')).runOutcomeCheck({stateCapability:state,planCapability:plan,sliceId:'SLICE-001',oracleId:'ORACLE-001',preparedSha256:a.prepared,seam:point=>{if(point===a.crash)process.kill(process.pid,'SIGKILL');}}).then(x=>process.stdout.write(JSON.stringify(x))).catch(e=>{process.stderr.write(e.stack);process.exitCode=1;});`;
async function fixture(t,program=false){const script="const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');test('heading',async()=>{await new Promise(r=>setTimeout(r,1000));assert.match(fs.readFileSync('README.md','utf8'),/New heading/);});";const f=await createPublicWorkflowFixture(t,program?{initialFiles:{'goal.test.cjs':script},planMutator:plan=>{const slice=plan.slices[0];slice.verification_commands=[{id:'CMD-001',gate_ids:['GATE-outcome-verification'],spec:{schema_version:1,executable:{kind:'node',value:'node'},args:['--test','goal.test.cjs'],cwd_role:'active-worktree',timeout_ms:5000,max_output_bytes:32768}}];slice.oracle_controls[0].source_refs=[{path:'goal.test.cjs',sha256:j.sha256(script)}];slice.oracle_controls[0].check={kind:'program',command_id:'CMD-001'};slice.oracle_controls[0].command_id='CMD-001';}}:{}),args=['--state',f.state,'--plan',f.planPath,'--slice','SLICE-001'];f.cli(['slice','activate',...args]);const scope=require('../runtime/plan-runtime.js').deriveScopedWriteAuthority({plan:f.plan,sliceId:'SLICE-001',writeClass:'production'});const w=f.cli(['implement','write','begin',...args,'--class','production','--scope-sha256',scope.sha256]);fs.writeFileSync(path.join(f.root,'README.md'),'New heading\n');f.cli(['implement','write','accept',...args,'--operation-id',w.operationId,'--pre-manifest-sha256',w.preManifestSha256]);const prepared=f.cli(['verification','outcome-explain',...args,'--oracle','ORACLE-001']);return{f,args,prepared};}
for(const crash of ['after-view-reservation','after-views-prepared','before-worker-start','after-worker-start'])test(`actual SIGKILL ${crash} recovers owned immutable views and retries without source rollback`,{
 skip:process.platform==='linux'&&crash==='after-worker-start'?'linux process identity unconfirmed':false,
},async t=>{
 const {f,args,prepared}=await fixture(t,crash==='after-worker-start');const input={root:f.root,state:f.state,plan:f.planPath,workDir:f.workDir,prepared:prepared.prepared_sha256,crash};
 const killed=cp.spawnSync(process.execPath,['-e',childCode,path.resolve(__dirname,'../runtime'),JSON.stringify(input)],{cwd:f.root,encoding:'utf8'});assert.equal(killed.signal,'SIGKILL',killed.stderr);assert(fs.existsSync(prepared.view_base));
 if(crash==='after-worker-start'){
  const quiet=path.join(prepared.view_base,'.runtime-quiescent.json'),waitUntil=Date.now()+15000;
  while(!fs.existsSync(quiet)){if(Date.now()>waitUntil)throw Error('worker did not confirm quiescence');await new Promise(resolve=>setTimeout(resolve,50));}
  const bytes=fs.readFileSync(quiet);fs.unlinkSync(quiet);let blocked=false;const expires=Date.now()+90000;
  while(!blocked){try{f.cli(['verification','outcome-run',...args,'--oracle','ORACLE-001','--prepared-digest',prepared.prepared_sha256]);assert.fail('unknown worker termination accepted');}catch(e){if(/outcome-view-termination-unconfirmed/.test(e.message)){blocked=true;break;}if(Date.now()>expires||!/lock-timeout|outcome-view-in-use/.test(e.message))throw e;await new Promise(resolve=>setTimeout(resolve,100));}}
  assert(fs.existsSync(prepared.view_base));fs.writeFileSync(quiet,bytes,{flag:'wx'});
 }
 let out;const deadline=Date.now()+90000;while(!out){try{out=f.cli(['verification','outcome-run',...args,'--oracle','ORACLE-001','--prepared-digest',prepared.prepared_sha256]);}catch(e){if(Date.now()>deadline||!/lock-timeout|outcome-view-in-use/.test(e.message))throw e;await new Promise(resolve=>setTimeout(resolve,100));}}assert.equal(out.positive.accepted,true);assert.equal(out.control.qualifying_failure,true);assert.equal(out.positive.physical_view_root,prepared.views.positive.root);assert.equal(fs.existsSync(prepared.view_base),false);assert.equal(fs.readFileSync(path.join(f.root,'README.md'),'utf8'),'New heading\n');
});
test('foreign directory and symlink at prepared view path stay untouched',async t=>{
 const {f,args,prepared}=await fixture(t);const marker='FOREIGN';fs.mkdirSync(prepared.view_base);fs.writeFileSync(path.join(prepared.view_base,marker),'user data');
 assert.throws(()=>f.cli(['verification','outcome-run',...args,'--oracle','ORACLE-001','--prepared-digest',prepared.prepared_sha256]),/outcome-view-owner/);assert.equal(fs.readFileSync(path.join(prepared.view_base,marker),'utf8'),'user data');fs.unlinkSync(path.join(prepared.view_base,marker));fs.rmdirSync(prepared.view_base);
 fs.symlinkSync(f.root,prepared.view_base,'dir');assert.throws(()=>f.cli(['verification','outcome-run',...args,'--oracle','ORACLE-001','--prepared-digest',prepared.prepared_sha256]),/outcome-view-owner/);assert(fs.lstatSync(prepared.view_base).isSymbolicLink());fs.unlinkSync(prepared.view_base);
});
