'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const p=require('../runtime/platform.js'),tx=require('../runtime/transaction-runtime.js'),j=require('../runtime/operation-journal.js'),o=require('../runtime/outcome-oracle-runtime.js');
const {assertOutcomeEvidenceWindow}=require('../runtime/outcome-evidence-window.js');
const api=require('../runtime/outcome-verification-runtime.js');
const {createPublicWorkflowFixture}=require('./helpers/public-workflow-fixtures.js');
const KIND='outcome-check-run-v1';
function caps(f,sliceId='SLICE-001') {const stateCapability=p.issueProjectStateCapability(f.root,f.state,{role:'session-state'}),sessionCapability=p.issueProjectStateCapability(f.root,f.workDir,{role:'session-work-dir',sessionStateCapability:stateCapability});return{stateCapability,planCapability:tx.issueSessionFileCapability({sessionCapability,candidate:f.planPath,allowedBasenames:['plan.json'],role:'locked-plan'}),sliceId};}
function journalFile(f,id){return path.join(f.root,'.claude',`deep-work.${f.sessionId}.op.${KIND}.${id}.json`);}
function simpleFixture(t){const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'outcome-window-'))),sessionId='s-12345678';t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.mkdirSync(path.join(root,'.claude'));const state=path.join(root,'.claude',`deep-work.${sessionId}.md`);fs.writeFileSync(state,`---\nsession_id: ${sessionId}\nwork_dir: .deep-work/${sessionId}\ncurrent_phase: implement\n---\n`);const stateCapability=p.issueProjectStateCapability(root,state,{role:'session-state'});return{root,sessionId,stateCapability,binding:{session_id:sessionId,slice_id:'SLICE-001',plan_authority_sha256:'a'.repeat(64),verification_plan_sha256:'b'.repeat(64),recovery_generation:1}};}
async function pending(f,changes={},stage='worker-authorized'){const preconditions={...f.binding,prepared_sha256:'c'.repeat(64),launch_id:crypto.randomUUID(),...changes};const operationId=`op-${o.digest(`${KIND}-operation`,preconditions)}`,op=await j.beginOperation({projectCapability:tx.projectCapabilityFor(f.stateCapability),sessionId:f.sessionId,kind:KIND,operationId,preconditions});for(const name of j.WORKFLOW_STAGE_RULES[KIND].slice(1,j.WORKFLOW_STAGE_RULES[KIND].indexOf(stage)+1))await j.recordOperationStage(op,name,{owned:{}});return op;}
test('only exact current authority with start authorization blocks, without reader mutations',async t=>{const f=simpleFixture(t);await pending(f,{slice_id:'SLICE-002'});await pending(f,{plan_authority_sha256:'d'.repeat(64)});await pending(f,{verification_plan_sha256:'e'.repeat(64)});await pending(f,{recovery_generation:0});await pending(f,{},'prepared');await pending(f,{},'views-owned');await j.beginOperation({projectCapability:tx.projectCapabilityFor(f.stateCapability),sessionId:f.sessionId,kind:'review-execution-run-v1',preconditions:{ongoing:true}});assert.doesNotThrow(()=>assertOutcomeEvidenceWindow(f));const blocked=await pending(f);const before=fs.readFileSync(journalFile(f,blocked.operationId));assert.throws(()=>assertOutcomeEvidenceWindow(f),/outcome-check-pending/);assert.deepEqual(fs.readFileSync(journalFile(f,blocked.operationId)),before);await j.completeOperation(blocked,{status:'abandoned-view'},{retainJournal:true});assert.doesNotThrow(()=>assertOutcomeEvidenceWindow(f));});
test('retained completed journals require a valid matching terminal ledger',async t=>{const f=simpleFixture(t),op=await pending(f);await j.completeOperation(op,{status:'terminal-test-result'},{retainJournal:true});assert.doesNotThrow(()=>assertOutcomeEvidenceWindow(f));const file=path.join(f.root,'.claude',`deep-work.${f.sessionId}.completed-operations.json`),ledger=JSON.parse(fs.readFileSync(file));ledger.receipts[0].result.status='tampered';fs.writeFileSync(file,JSON.stringify(ledger));assert.throws(()=>assertOutcomeEvidenceWindow(f),/outcome-evidence-window-invalid/);});
test('journal identity and stage tampering cannot create an authenticated exception',async t=>{const f=simpleFixture(t),op=await pending(f),file=journalFile(f,op.operationId),value=JSON.parse(fs.readFileSync(file));value.preconditions.slice_id='SLICE-002';fs.writeFileSync(file,JSON.stringify(value));assert.throws(()=>assertOutcomeEvidenceWindow(f),/outcome-evidence-window-invalid/);value.preconditions.slice_id='SLICE-001';value.stage='prepared';fs.writeFileSync(file,JSON.stringify(value));assert.throws(()=>assertOutcomeEvidenceWindow(f),/outcome-evidence-window-invalid/);});
test('oversized and nonregular journals are bounded unavailable evidence',async t=>{const f=simpleFixture(t),op=await pending(f),file=journalFile(f,op.operationId);fs.truncateSync(file,1024*1024+1);assert.throws(()=>assertOutcomeEvidenceWindow(f),/outcome-evidence-window-invalid/);fs.unlinkSync(file);fs.mkdirSync(file);assert.throws(()=>assertOutcomeEvidenceWindow(f),/outcome-evidence-window-invalid/);});
function base(f,slice='SLICE-001'){return['--state',f.state,'--plan',f.planPath,'--slice',slice];}
test('rejected in-use retry retires only its effect-free prepared operation; signed recovery allows proof and park',{
 skip:process.platform==='linux'?'linux process identity unconfirmed':false,
},async t=>{
 const script="const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');test('heading',async()=>{await new Promise(r=>setTimeout(r,3000));assert.match(fs.readFileSync('README.md','utf8'),/New heading/);});";
 const f=await createPublicWorkflowFixture(t,{initialReadme:'New heading\n',initialFiles:{'goal.test.cjs':script},planMutator:plan=>{const slice=plan.slices[0];slice.verification_commands=[{id:'CMD-001',gate_ids:['GATE-outcome-verification'],spec:{schema_version:1,executable:{kind:'node',value:'node'},args:['--test','goal.test.cjs'],cwd_role:'active-worktree',timeout_ms:10000,max_output_bytes:32768}}];Object.assign(slice.oracle_controls[0],{source_refs:[{path:'goal.test.cjs',sha256:o.hash(script)}],command_id:'CMD-001',check:{kind:'program',command_id:'CMD-001'}});}});
 f.cli(['slice','activate',...base(f)]);f.cli(['outcome','source','observe',...base(f)]);
 const prepared=f.cli(['verification','outcome-explain',...base(f),'--oracle','ORACLE-001']),args={...caps(f),oracleId:'ORACLE-001',preparedSha256:prepared.prepared_sha256};
 await assert.rejects(api.runOutcomeCheck({...args,seam:name=>{if(name==='after-worker-start')throw new Error('program-interruption');}}),/program-interruption/);
 await assert.rejects(api.runOutcomeCheck(args),/outcome-view-in-use/);
 const projectCapability=tx.projectCapabilityFor(args.stateCapability),rows=j.listCompletedOperations({projectCapability,sessionId:f.sessionId});
 assert(rows.some(row=>row.kind===KIND&&row.result.status==='abandoned-before-view'));
 await waitForQuiet(prepared);
 const pair=await api.runOutcomeCheck(args);
 assert(api.authenticateOutcomeCheck({...args,ref:pair.ref}).positive.accepted);
 const journals=fs.readdirSync(path.join(f.root,'.claude')).filter(name=>name.includes('.op.outcome-check-run-v1.'));
 assert.deepEqual(journals,[]);
 assert.equal(f.cli(['session','park','--state',f.state,'--session',f.sessionId]).status,'parked');
});
function refs(f,pair,prepared){const write=(name,value)=>f.write(path.relative(f.root,path.join(f.workDir,name)),value);return{positive:write('window-positive.json',[pair.positiveRef]),control:write('window-control.json',[pair.controlRef]),empty:write('window-executions.json',[]),source:write('window-source.json',prepared.source_evidence),write};}
function publishReview(f,r){return f.cli(['outcome','review','publish',...base(f),'--positive-refs-json',r.positive,'--control-refs-json',r.control,'--review-execution-refs-json',r.empty]);}
function complete(f,r,review){return f.cli(['implement','outcome-complete',...base(f),'--positive-refs-json',r.positive,'--control-refs-json',r.control,'--review-ref-json',r.write('window-review.json',review.ref),'--source-evidence-json',r.source]);}
async function waitForQuiet(prepared){const marker=path.join(prepared.view_base,'.runtime-quiescent.json'),deadline=Date.now()+15000;while(!fs.existsSync(marker)&&Date.now()<deadline)await new Promise(r=>setTimeout(r,25));assert(fs.existsSync(marker),'real worker published signed quiescence');await new Promise(r=>setTimeout(r,100));}
test('public old pair/review cannot complete across a newer interrupted worker; signed retry restores completion',async t=>{const f=await createPublicWorkflowFixture(t,{initialReadme:'New heading\n'});f.cli(['slice','activate',...base(f)]);f.cli(['outcome','source','observe',...base(f)]);const prepared=f.cli(['verification','outcome-explain',...base(f),'--oracle','ORACLE-001']);const first=f.cli(['verification','outcome-run',...base(f),'--oracle','ORACLE-001','--prepared-digest',prepared.prepared_sha256]),r=refs(f,first,prepared),review=publishReview(f,r),args=caps(f);await assert.rejects(api.runOutcomeCheck({...args,oracleId:'ORACLE-001',preparedSha256:prepared.prepared_sha256,seam:name=>{if(name==='after-worker-start')throw Object.assign(new Error('test-interruption'),{code:'test-interruption'});}}),/test-interruption/);await waitForQuiet(prepared);assert.throws(()=>api.authenticateOutcomeCheck({...args,ref:first.ref}),/outcome-check-pending/);assert.throws(()=>publishReview(f,r),/outcome-check-pending/);assert.throws(()=>complete(f,r,review),/outcome-check-pending/);assert.equal(f.fields().active_slice,'SLICE-001');const next=f.cli(['verification','outcome-run',...base(f),'--oracle','ORACLE-001','--prepared-digest',prepared.prepared_sha256]);assert.notEqual(next.ref.producer_operation_id,first.ref.producer_operation_id);const fresh=refs(f,next,prepared);assert(complete(f,fresh,publishReview(f,fresh)).publication);});
test('actual sibling worker interruption does not invalidate healthy slice proof',async t=>{const f=await createPublicWorkflowFixture(t,{initialReadme:'New heading\n',planMutator:plan=>{const sibling=structuredClone(plan.slices[0]);sibling.id='SLICE-002';sibling.contract.id='SLICE-002';sibling.oracle_controls[0].id='ORACLE-002';plan.slices.push(sibling);}});f.cli(['slice','activate',...base(f)]);f.cli(['outcome','source','observe',...base(f)]);const prepared=f.cli(['verification','outcome-explain',...base(f),'--oracle','ORACLE-001']),first=f.cli(['verification','outcome-run',...base(f),'--oracle','ORACLE-001','--prepared-digest',prepared.prepared_sha256]),r=refs(f,first,prepared);complete(f,r,publishReview(f,r));f.cli(['slice','activate',...base(f,'SLICE-002')]);f.cli(['outcome','source','observe',...base(f,'SLICE-002')]);const sibling=f.cli(['verification','outcome-explain',...base(f,'SLICE-002'),'--oracle','ORACLE-002']);await assert.rejects(api.runOutcomeCheck({...caps(f,'SLICE-002'),oracleId:'ORACLE-002',preparedSha256:sibling.prepared_sha256,seam:name=>{if(name==='after-worker-start')throw new Error('sibling-interruption');}}),/sibling-interruption/);await waitForQuiet(sibling);assert(api.authenticateOutcomeCheck({...caps(f),ref:first.ref}).positive.accepted);await require('../runtime/outcome-view-lifecycle.js').cleanExisting({stateCapability:caps(f).stateCapability,prepared:sibling});});
