'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process');
const plugin=fs.realpathSync(path.resolve(__dirname,'..')),cliPath=path.join(plugin,'scripts/deep-work-runtime.js');
function setup(t,{args=[],profileDefaults}={}){
 const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'dw-init-profile-')));t.after(()=>{const rows=cp.spawnSync('git',['worktree','list','--porcelain'],{cwd:root,encoding:'utf8'}).stdout||'';for(const line of rows.split('\n'))if(line.startsWith('worktree ')&&line.slice(9)!==root)cp.spawnSync('git',['worktree','remove','--force',line.slice(9)],{cwd:root});fs.rmSync(root,{recursive:true,force:true});});
 const git=args=>cp.execFileSync('git',args,{cwd:root,stdio:'pipe'});git(['init','-q']);git(['config','user.name','Fixture']);git(['config','user.email','fixture@example.invalid']);fs.writeFileSync(path.join(root,'README.md'),'fixture\n');fs.writeFileSync(path.join(root,'.gitignore'),'.claude/\n.deep-work/\n.setup/\n');git(['add','README.md','.gitignore']);git(['commit','-qm','fixture']);
 const write=(name,value)=>{const file=path.join(root,'.setup',name);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,typeof value==='string'?value:JSON.stringify(value));return file;};
 const cli=args=>{const result=cp.spawnSync(process.execPath,[cliPath,...args],{cwd:root,encoding:'utf8',env:{...process.env,DEEP_WORK_SESSION_ID:''}});if(result.status!==0)throw new Error(`${args.slice(0,3).join(' ')}: ${result.stderr}`);return JSON.parse(result.stdout);};
 const profilePath=path.join(root,'.setup/profile.yaml');cli(['profile','migrate','--profile-file',profilePath]);if(profileDefaults)cli(['profile','update','--profile-file',profilePath,'--reason','setup','--preset','regression','--defaults-json',write('profile-update.json',profileDefaults)]);
 const profile=cli(['profile','load','--profile-file',profilePath]),profileFile=write('profile.json',profile),flags=cli(['flags','parse','--arguments-json',write('args.json',args)]),flagsFile=write('flags.json',flags),taskFile=write('task.txt','Update README wording');
 const initialized=cli(['session','initialize','--task-file',taskFile,'--flags-json',flagsFile,'--profile-json',profileFile]);
 const prepare=()=>cli(['session','repository','prepare','--session',initialized.sessionId,'--mode',initialized.mode,'--task-file',taskFile,'--defaults-json',write('effective-defaults.json',initialized.defaults),'--profile-json',profileFile]);
 const fields=state=>require(path.join(plugin,'runtime/frontmatter.js')).parseFrontmatter(fs.readFileSync(state,'utf8')).fields;
 return{root,profile,flags,initialized,prepare,fields,cli,write};
}
test('shipped create/load profile auto reaches real repository prepare with returned defaults',t=>{const f=setup(t);assert.equal(f.profile.defaults.model_routing,'auto');const prepared=f.prepare(),state=f.fields(prepared.stateCapability.path);assert.equal(f.initialized.mode,'new-branch');assert.equal(state.repository_mode,'new-branch');assert.equal(state.team_mode,'solo');assert.equal(state.execution_override,null);assert.equal(state.execution_mode,'inline');assert.deepEqual(state.model_routing,['brainstorm=main','research=main','spec=main','plan=main','implement=main','test=main']);assert.equal(f.cli(['session','authority','validate','--state',prepared.stateCapability.path]).status,'pre-plan');});
test('parsed explicit delegate/team/model and no-branch override survive init and resume',t=>{const f=setup(t,{args:['--exec=delegate','--team','--no-branch','--model-routing=implement=gpt-6-astra']});const prepared=f.prepare(),state=f.fields(prepared.stateCapability.path);assert.equal(f.initialized.mode,'current-branch');assert.equal(f.initialized.defaults.exec_mode,'delegate');assert.equal(f.initialized.defaults.team_mode,'team');assert.equal(state.execution_override,'delegate');assert.equal(state.execution_mode,'delegate');assert.equal(state.team_mode,'team');assert.deepEqual(state.model_routing,['implement=gpt-6-astra']);const bytes=fs.readFileSync(prepared.stateCapability.path);f.cli(['session','authority','validate','--state',prepared.stateCapability.path]);f.cli(['session','state','migrate-model-routing','--state',prepared.stateCapability.path,'--session',f.initialized.sessionId]);assert.deepEqual(fs.readFileSync(prepared.stateCapability.path),bytes);});
test('explicit inline wins team transport while preserving the profile team and concrete model pin',t=>{const f=setup(t,{args:['--exec=inline'],profileDefaults:{team_mode:'team',start_phase:'research',tdd_mode:'adaptive',git:{use_worktree:false,use_branch:false},model_routing:'implement=gpt-6-astra'}});const prepared=f.prepare(),state=f.fields(prepared.stateCapability.path);assert.equal(f.initialized.mode,'current-branch');assert.equal(state.team_mode,'team');assert.equal(state.execution_override,'inline');assert.equal(state.execution_mode,'inline');assert.deepEqual(state.model_routing,['implement=gpt-6-astra']);});
test('profile true worktree flag takes precedence over branch without Boolean string coercion',t=>{const f=setup(t,{profileDefaults:{team_mode:'solo',start_phase:'research',tdd_mode:'adaptive',git:{use_worktree:true,use_branch:true},model_routing:'auto'}});const prepared=f.prepare(),state=f.fields(prepared.stateCapability.path);assert.equal(f.initialized.mode,'worktree');assert.equal(state.repository_mode,'worktree');assert.equal(state.worktree_enabled,true);assert.equal(fs.existsSync(state.worktree_path),true);});
