'use strict';const test=require('node:test'),assert=require('node:assert/strict');
const {createPublicWorkflowFixture}=require('./helpers/public-workflow-fixtures.js');
test('fresh CLI init and pre-plan resume preserve version and reserved identity',async t=>{const f=await createPublicWorkflowFixture(t,{checkpoint:'research'});assert.equal(f.fields().created_by_version,require('../.claude-plugin/plugin.json').version);assert.match(f.fields().session_m3_run_id,/^[0-9A-HJKMNP-TV-Z]{26}$/);assert.equal(f.cli(['session','authority','validate','--state',f.state]).status,'pre-plan');});
test('actual low compact outcome plan approval and continue are reachable',async t=>{const f=await createPublicWorkflowFixture(t);assert.equal(f.fields().plan_bound_once,true);assert.equal(f.fields().current_phase,'implement');assert.equal(JSON.parse(f.fields().verification_plan_json).schema_version,3);f.cli(['slice','activate','--state',f.state,'--plan',f.planPath,'--slice','SLICE-001']);assert.equal(f.fields().tdd_state,'NOT_APPLICABLE');});
test('help is side effect free and advertises concrete continuation and outcome flags',()=>{const cp=require('node:child_process');const out=JSON.parse(cp.execFileSync(process.execPath,[require.resolve('../scripts/deep-work-runtime.js'),'--help'],{encoding:'utf8'}));assert(out.routes.some(r=>r.id==='phase continue'));assert.deepEqual(out.routes.find(r=>r.id==='verification outcome-run').required,['state','plan','slice','oracle','prepared-digest']);});

test('phase completion preserves reviewed artifacts and monotonic plan history',()=>{const phase=require('../runtime/phase-runtime.js');const review=JSON.stringify({spec:{result:'PASS',structural_json_sha256:'a'.repeat(64)}});const completed=phase.completePhase({state:{phase_review:review,plan_bound_once:true},phase:'spec',result:{summary:'done'},at:'2026-09-06T00:00:00Z'});assert.equal(completed.phase_review,review);assert.equal(phase.rerunPhase({state:completed,phase:'plan'}).plan_bound_once,true);});
test('strict requested method and tested TAP policy are real session authority before writes',async t=>{const f=await createPublicWorkflowFixture(t,{method:'strict',basis:'strict-tdd-v2'});assert.equal(f.fields().execution_method,'strict');assert.deepEqual(f.plan.execution_policy.strict_required_slice_ids,['SLICE-001']);f.cli(['slice','activate','--state',f.state,'--plan',f.planPath,'--slice','SLICE-001']);assert.equal(f.fields().tdd_state,'PENDING');const scope=require('../runtime/plan-runtime.js').deriveScopedWriteAuthority({plan:f.plan,sliceId:'SLICE-001',writeClass:'production'});assert.throws(()=>f.cli(['implement','write','begin','--state',f.state,'--plan',f.planPath,'--slice','SLICE-001','--class','production','--scope-sha256',scope.sha256]),/scoped-write-tdd-state/);});
test('same-risk policy change goes through authenticated discovery and opens replan epoch',async t=>{const f=await createPublicWorkflowFixture(t);const path=require('node:path'),fs=require('node:fs'),j=require('../runtime/operation-journal.js');const source=path.join(f.workDir,'plan.md');const obs=f.write(path.relative(f.root,path.join(f.workDir,'policy-observation.json')),{schema_version:1,reason:'verification-policy-change',scope:'slice',slice_id:'SLICE-001',requirement_id:'REQ-001',invariant_id:null,failure_mode_id:null,source_path:path.relative(f.root,source),source_sha256:j.sha256(fs.readFileSync(source)),detail_code:'new-supported-node-policy'});const pub=f.cli(['replan','discovery','publish','--state',f.state,'--plan',f.planPath,'--observation-json',obs]);f.cli(['replan','discovery','dispatch','--state',f.state,'--plan',f.planPath,'--slice','SLICE-001','--producer-operation-id',pub.operation_id]);assert.equal(f.fields().replan_required,true);assert.match(f.fields().active_replan_epoch_id,/^[a-f0-9]{64}$/);assert.equal(f.fields().plan_bound_once,true);});

test('a forged pre-plan latch cannot erase actual approved plan history',async t=>{const f=await createPublicWorkflowFixture(t),fs=require('node:fs'),fm=require('../runtime/frontmatter.js');fs.writeFileSync(f.state,fm.updateFrontmatterText(fs.readFileSync(f.state,'utf8'),{current_phase:'research',plan_bound_once:false}));assert.throws(()=>f.cli(['session','authority','validate','--state',f.state]),/prior-plan-authority/);});
test('concurrent activation serializes and cannot overwrite another active slice',async t=>{const f=await createPublicWorkflowFixture(t,{planMutator:plan=>{const second=structuredClone(plan.slices[0]);second.id=second.contract.id='SLICE-002';plan.slices.push(second);}});const cp=require('node:child_process'),util=require('node:util'),run=util.promisify(cp.execFile),runtime=require.resolve('../scripts/deep-work-runtime.js');const rows=await Promise.allSettled(['SLICE-001','SLICE-002'].map(slice=>run(process.execPath,[runtime,'slice','activate','--state',f.state,'--plan',f.planPath,'--slice',slice],{cwd:f.root})));assert.equal(rows.filter(r=>r.status==='fulfilled').length,1,JSON.stringify(rows.map(r=>({status:r.status,error:r.reason?.stderr}))));assert.equal(rows.filter(r=>r.status==='rejected'&&/slice-active-conflict|session-file-state-drift|session-capability|path-identity|path-capability-identity|path-changed/.test(r.reason.stderr)).length,1,JSON.stringify(rows.map(r=>r.reason?.stderr)));assert(['SLICE-001','SLICE-002'].includes(f.fields().active_slice));});
