'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {createPublicWorkflowFixture}=require('./helpers/public-workflow-fixtures.js'),fm=require('../runtime/frontmatter.js'),platform=require('../runtime/platform.js');
function set(f,patch){fs.writeFileSync(f.state,fm.updateFrontmatterText(fs.readFileSync(f.state,'utf8'),patch));}
function park(f){return f.cli(['session','park','--state',f.state,'--session',f.sessionId]);}
function restore(f){return f.cli(['session','restore','--state',f.state,'--session',f.sessionId]);}
test('future minor writer rejected without changing parked archive or registry',async t=>{const f=await createPublicWorkflowFixture(t,{checkpoint:'research'});set(f,{created_by_version:'7.5.0'});const parked=park(f),bytes=fs.readFileSync(f.state);assert.throws(()=>restore(f),/session-reader-unavailable/);assert.deepEqual(fs.readFileSync(f.state),bytes);assert.equal(f.fields().parked,true);assert.equal(fs.existsSync(path.join(f.root,parked.archive_ref.path)),true);});
test('future state schema rejected despite supported writer',async t=>{const f=await createPublicWorkflowFixture(t,{checkpoint:'research'});set(f,{schema_version:3});park(f);assert.throws(()=>restore(f),/session-schema-unavailable/);assert.equal(f.fields().parked,true);});
test('actual source drift restores into authenticated active replan and cannot reuse stale completion',async t=>{const f=await createPublicWorkflowFixture(t,{checkpoint:'implement'});set(f,{test_passed:true,test_pass_operation_id:'op-'+ 'a'.repeat(64),outcome_receipt_refs_json:JSON.stringify({'SLICE-001':{stale:true}}),outcome_review_ref_json:'{"stale":true}'});const parked=park(f),archive=fs.readFileSync(path.join(f.root,parked.archive_ref.path));fs.writeFileSync(path.join(f.root,'README.md'),'Externally changed source\n');const result=restore(f);assert.equal(result.status,'replan-required');const state=f.fields();assert.equal(state.current_phase,'spec');assert.equal(state.replan_required,true);assert.equal(state.parked,false);assert.equal(state.plan_bound_once,true);assert.equal(state.test_passed,false);assert.equal(state.test_pass_operation_id,null);assert.equal(state.outcome_receipt_refs_json,'{}');assert.equal(state.verification_plan_json,null);assert.match(state.active_replan_epoch_id,/^[a-f0-9]{64}$/);assert.equal(state.receipt_recovery_generation,1);assert.deepEqual(fs.readFileSync(path.join(f.root,parked.archive_ref.path)),archive);assert.equal(f.cli(['session','authority','validate','--state',f.state]).status,'replan-active');assert.throws(()=>f.cli(['slice','activate','--state',f.state,'--plan',f.planPath,'--slice','SLICE-001']),/dispatcher-phase/);f.cli(['phase','begin','--state',f.state,'--phase','spec','--at','2026-09-07T00:00:00Z']);assert.equal(f.fields().artifact_approval_consumptions_json,null);assert.throws(()=>f.cli(['phase','continue','--state',f.state]),/spec-approval-required/);assert.equal(f.fields().current_phase,'spec');assert.deepEqual(fs.readFileSync(path.join(f.root,parked.archive_ref.path)),archive);});
test('restore replan recovers crash before epoch and reuses operation, archive and generation',async t=>{const f=await createPublicWorkflowFixture(t);const parked=park(f);fs.writeFileSync(path.join(f.root,'README.md'),'drift');const stateCapability=platform.issueProjectStateCapability(f.root,f.state,{role:'session-state'});await assert.rejects(()=>require('../runtime/session-maintenance-runtime.js').restoreSession({stateCapability,sessionId:f.sessionId,seam:point=>{if(point==='after-restore-replan-state')throw new Error('simulated-crash');}}),/simulated-crash/);const operation=f.fields().restore_operation_id;const result=restore(f);assert.equal(result.status,'replan-required');assert.equal(f.fields().restore_operation_id,operation);assert.equal(f.fields().receipt_recovery_generation,1);assert.equal(restore(f).adopted,true);assert.equal(fs.existsSync(path.join(f.root,parked.archive_ref.path)),true);});
test('unchanged source retains exact successful historical replay',async t=>{const f=await createPublicWorkflowFixture(t,{checkpoint:'research'}),bytes=fs.readFileSync(f.state);park(f);assert.equal(restore(f).status,'restored');assert.deepEqual(fs.readFileSync(f.state),bytes);assert.equal(restore(f).adopted,true);assert.deepEqual(fs.readFileSync(f.state),bytes);});
test('source-drift restore refuses another session pointer before de-parking',async t=>{const f=await createPublicWorkflowFixture(t);park(f);fs.writeFileSync(path.join(f.root,'README.md'),'drift');fs.writeFileSync(path.join(f.root,'.claude/deep-work-current-session'),'s-aaaaaaaa\n');const before=fs.readFileSync(f.state);assert.throws(()=>restore(f),/session-restore-pointer-conflict/);assert.deepEqual(fs.readFileSync(f.state),before);assert.equal(fs.readFileSync(path.join(f.root,'.claude/deep-work-current-session'),'utf8'),'s-aaaaaaaa\n');});
test('pre-plan source drift returns to research with no fabricated plan epoch or completion',async t=>{const f=await createPublicWorkflowFixture(t,{checkpoint:'research'}),parked=park(f);fs.writeFileSync(path.join(f.root,'README.md'),'drift');assert.equal(restore(f).status,'review-required');assert.equal(f.fields().current_phase,'research');assert.equal(f.fields().parked,false);assert.equal(f.fields().plan_bound_once,false);assert.equal(f.fields().test_passed,false);assert.equal(f.fields().active_replan_epoch_id,undefined);assert.equal(f.cli(['session','authority','validate','--state',f.state]).status,'pre-plan');f.cli(['phase','continue','--state',f.state]);assert.equal(f.fields().current_phase,'spec');assert.equal(fs.existsSync(path.join(f.root,parked.archive_ref.path)),true);});
test('unknown receipt payload schema and unknown bound policy reject before de-parking',async t=>{for(const kind of ['receipt','policy']){const f=await createPublicWorkflowFixture(t,{checkpoint:'research'});if(kind==='receipt'){fs.mkdirSync(path.join(f.workDir,'receipts'));fs.writeFileSync(path.join(f.workDir,'receipts/SLICE-001.json'),JSON.stringify({schema_version:'1.0',envelope:{schema:{version:'1.2'}},payload:{schema_version:'1.2'}}));}else set(f,{methodology_policy_json:'{"schema_version":99}'});park(f);const before=fs.readFileSync(f.state);assert.throws(()=>restore(f),/session-receipt-schema-unavailable|session-policy-unavailable/);assert.deepEqual(fs.readFileSync(f.state),before);}});
