'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const runtime=require('./global-findings-runtime.js'),j=require('./operation-journal.js'),platform=require('./platform.js');
const empty={projection:{status:'unknown',points:[]},warnings:['finding-ref-invalid']};
const execution=findings=>({review_operation_id:'op-'+'a'.repeat(64),observation:{response:{findings}}});
function fixture(t){const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'dw-global-findings-'))),workDir=path.join(root,'.deep-work/s-1234abcd');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.mkdirSync(path.join(root,'.claude'));fs.mkdirSync(workDir,{recursive:true});const state=path.join(root,'.claude/deep-work.s-1234abcd.md');fs.writeFileSync(state,'---\nsession_id: s-1234abcd\n---\n');return{root,workDir,stateCapability:platform.issueProjectStateCapability(root,state,{role:'session-state'}),fields:{}};}
test('actual review observation projection preserves open advisory and explicit resolved findings',()=>{const p=runtime.projectExecutions([execution([{id:'FIND-001',blocking:false,severity:'low'},{id:'FIND-002',blocking:false,severity:'info',status:'resolved'}])]);assert.equal(p.status,'open');assert.deepEqual(p.points[0].open_ids,['FIND-001']);assert.deepEqual(p.points[0].resolved_ids,['FIND-002']);const merged=runtime.mergeFindingProjections({legacy:empty,legacyRequired:false,global:p});assert.equal(merged.projection.status,'open');assert.deepEqual(merged.warnings,[]);});
test('missing or corrupt legacy obligations remain unknown despite complete global review',()=>{const global=runtime.projectExecutions([execution([])]);assert.equal(runtime.mergeFindingProjections({legacy:empty,legacyRequired:true,global}).projection.status,'unknown');assert.equal(runtime.mergeFindingProjections({legacy:empty,legacyRequired:false,global:null}).projection.status,'unknown');const point={point:'spec',round:2,open_ids:['REV-SEMANTIC-001'],resolved_ids:[],unknown_ids:[]};const old={projection:{status:'open',points:[point]},warnings:[]};assert.deepEqual(runtime.mergeFindingProjections({legacy:old,legacyRequired:true,global}).projection.points.find(row=>row.point==='spec'),point);});
test('legacy index, completed and pending producers, and old refs remain required',async t=>{const f=fixture(t);assert.equal(runtime.legacyFindingsRequired(f),false);assert.equal(runtime.legacyFindingsRequired({...f,fields:{governed_finding_refs_json:'broken'}}),true);const projectCapability=platform.issueProjectStateCapability(f.root,f.root,{role:'project-root'}),op=await j.beginOperation({projectCapability,sessionId:'s-1234abcd',kind:'finding-publish',preconditions:{fixture:true}});assert.equal(runtime.legacyFindingsRequired(f),true);await j.completeOperation(op,{fixture:true});assert.equal(runtime.legacyFindingsRequired(f),true);const second=fixture(t);fs.mkdirSync(path.join(second.workDir,'reviews/refs'),{recursive:true});fs.writeFileSync(path.join(second.workDir,'reviews/refs/old.json'),'{}');assert.equal(runtime.legacyFindingsRequired(second),true);});
test('foreign, missing or uncommitted global review cannot erase legacy unknown',t=>{const f=fixture(t);const actual=runtime.loadV3FindingProjection({...f,plan:{schema_version:3},verificationPlan:{},legacy:empty});assert.equal(actual.projection.status,'unknown');assert.deepEqual(runtime.loadV3FindingProjection({...f,plan:{schema_version:2},legacy:empty}),empty);assert.throws(()=>runtime.projectExecutions([execution([{id:'same'},{id:'same'}])]),/duplicate/);});
